server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: dumservice
          uri: lb://dummie-service/
          predicates:
            - Path=/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/**
