server:
   port:8090

spring:
   cloud:
      gateway:
      discovery:
         locator:
            enabled: true
      routes:
         - id: dummie-service
            predicates:
            - Path=/dimmieservice/**
         - id: restaurants
            predicates:
            - Path=/restaurant/**
